using System;
using System.IO;
using System.Net;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Threading;
using System.Runtime.InteropServices;

namespace GameDictApp {
    public class Program {
        private static System.Threading.Mutex appMutex;
        [STAThread]
        public static void Main(string[] args) {
            bool createdNew;
            appMutex = new System.Threading.Mutex(true, "GameDictAI_SingleInstance_Mutex", out createdNew);
            if (!createdNew) {
                return;
            }
            string _lp=System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"GameDict","gamedict.log");
            System.IO.Directory.CreateDirectory(System.IO.Path.GetDirectoryName(_lp));
            try{using(var _fs2=new System.IO.FileStream(_lp,System.IO.FileMode.Append,System.IO.FileAccess.Write,System.IO.FileShare.ReadWrite))
                using(var _sw2=new System.IO.StreamWriter(_fs2,System.Text.Encoding.UTF8))
                    _sw2.Write(System.DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff")+" [INFO ] App.Main start\n");}catch{}
            AppDomain.CurrentDomain.UnhandledException+=(s,e)=>{try{System.IO.File.AppendAllText(_lp,System.DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff")+" [FATAL] "+e.ExceptionObject+"\n",System.Text.Encoding.UTF8);}catch{}};
            try { new App().Run(new MainWindow()); }
            catch(Exception ex){try{System.IO.File.AppendAllText(_lp,System.DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff")+" [FATAL] "+ex.ToString()+"\n",System.Text.Encoding.UTF8);}catch{}}
        }
    }
    public class App : Application {
        protected override void OnStartup(StartupEventArgs e) { base.OnStartup(e); }
    }
    // Standalone config: %APPDATA%\GameDict\gamedict.toml
    public static class GameDictConfig {
        public static readonly string ConfigPath=System.IO.Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"GameDict","gamedict.toml");
        // Load from standalone config; returns false if file doesn't exist
        public static bool Load(out string apiBase,out string apiKey,out string model,out string useVision,out double floatX,out double floatY){
            apiBase=null;apiKey=null;model=null;useVision=null;floatX=-1;floatY=-1;
            try{
                if(!File.Exists(ConfigPath))return false;
                foreach(string line in File.ReadAllLines(ConfigPath)){
                    string t=line.Trim(); int q1,q2;
                    if(t.StartsWith("api_base")){q1=t.IndexOf('"');q2=t.LastIndexOf('"');if(q1>=0&&q2>q1)apiBase=t.Substring(q1+1,q2-q1-1);}
                    if(t.StartsWith("api_key")){q1=t.IndexOf('"');q2=t.LastIndexOf('"');if(q1>=0&&q2>q1)apiKey=t.Substring(q1+1,q2-q1-1);}
                    if(t.StartsWith("model")){q1=t.IndexOf('"');q2=t.LastIndexOf('"');if(q1>=0&&q2>q1)model=t.Substring(q1+1,q2-q1-1);}
                    if(t.StartsWith("use_vision")){useVision=t.Contains("true")?"true":null;}
                    if(t.StartsWith("float_x=")||t.StartsWith("float_x ")){double.TryParse(t.Split('=')[1].Trim(),out floatX);}
                    if(t.StartsWith("float_y=")||t.StartsWith("float_y ")){double.TryParse(t.Split('=')[1].Trim(),out floatY);}
                }
                return true;
            }catch(Exception ex){Logger.Error("GameDictConfig.Load",ex);return false;}
        }
        public static void Save(string apiBase,string apiKey,string model,bool useVision=true,double floatX=-1,double floatY=-1){
            try{
                Directory.CreateDirectory(System.IO.Path.GetDirectoryName(ConfigPath));
                var sb=new System.Text.StringBuilder();
                sb.AppendLine("# GameDict AI configuration");
                sb.AppendLine("# Generated by GameDict AI - do not edit while app is running");
                sb.AppendLine();
                sb.AppendLine("api_base   = \""+apiBase+"\"");
                sb.AppendLine("api_key    = \""+apiKey+"\"");
                sb.AppendLine("model      = \""+model+"\"");
                sb.AppendLine("use_vision = "+(useVision?"true":"false"));
                if(floatX>=0&&floatY>=0){
                    sb.AppendLine("float_x    = "+((int)floatX));
                    sb.AppendLine("float_y    = "+((int)floatY));
                }
                File.WriteAllText(ConfigPath,sb.ToString(),System.Text.Encoding.UTF8);
                Logger.Info("Config saved to "+ConfigPath);
            }catch(Exception ex){Logger.Error("GameDictConfig.Save",ex);}
        }
        public static void SavePosition(double x,double y){
            try{
                if(!File.Exists(ConfigPath))return;
                var list=new System.Collections.Generic.List<string>(File.ReadAllLines(ConfigPath));
                list.RemoveAll(l=>l.Trim().StartsWith("float_x")||l.Trim().StartsWith("float_y"));
                list.Add("float_x    = "+((int)x));
                list.Add("float_y    = "+((int)y));
                File.WriteAllLines(ConfigPath,list.ToArray(),System.Text.Encoding.UTF8);
            }catch{}
        }
    }

    public class MainWindow : Window {
        private const int  HOTKEY_ID_CTRL_T = 9001;
        private const int  HOTKEY_ID_ALT_Q  = 9002;
        private const uint MOD_ALT=0x0001,MOD_CONTROL=0x0002,MOD_NOREPEAT=0x4000;
        private const uint VK_T=0x54,VK_Q=0x51;
        private const int  WM_HOTKEY=0x0312;
        [DllImport("user32.dll")] private static extern bool RegisterHotKey(IntPtr hWnd,int id,uint fsModifiers,uint vk);
        [DllImport("user32.dll")] private static extern bool UnregisterHotKey(IntPtr hWnd,int id);
        [DllImport("user32.dll")] private static extern bool GetCursorPos(out POINT lpPoint);
        [DllImport("user32.dll")] private static extern uint GetClipboardSequenceNumber();
        [StructLayout(LayoutKind.Sequential)] public struct POINT{public int X,Y;}
        private TextBlock  statusText;
        private ListBox    historyList;
        private List<HistoryEntry> historyItems=new List<HistoryEntry>();
        private Border     rootBorder;
        private IntPtr     windowHandle;
        private System.Windows.Forms.NotifyIcon trayIcon;
        public FloatingResultWindow floatingWin;
        public string currentModel="gemini-3.8-flash-high";
        public string apiKey="";
        public string apiBase="https://ai.kncloud.top/v1/chat/completions";
        public bool   useVision=true; // false = OCR + text-only model
        public MainWindow() {
            try{byte[] _ib=Convert.FromBase64String(EmbeddedIcon.IcoB64);var _ms=new System.IO.MemoryStream(_ib);var _dec=new System.Windows.Media.Imaging.IconBitmapDecoder(_ms,System.Windows.Media.Imaging.BitmapCreateOptions.None,System.Windows.Media.Imaging.BitmapCacheOption.OnLoad);if(_dec.Frames.Count>0){var _fr=_dec.Frames[0];_fr.Freeze();this.Icon=_fr;}}catch(Exception _ex){Logger.Error("WindowIcon",_ex);}
            LoadCodexConfig(); Logger.Info("Config model="+currentModel);
            InitUI(); InitTray();
            floatingWin=new FloatingResultWindow();
            // 如果已读取到历史位置，设置给 floatingWin
            string _b,_k,_m,_v; double _fx,_fy;
            if(GameDictConfig.Load(out _b,out _k,out _m,out _v,out _fx,out _fy)){
                if(_fx>=0&&_fy>=0){floatingWin.LastX=_fx;floatingWin.LastY=_fy;floatingWin.HasCustomPosition=true;}
            }
            this.Loaded+=MainWindow_Loaded; this.Hide(); this.Closing+=MainWindow_Closing;
            // Restore history
            var saved=HistoryStore.Load();
            // Newest saved entry should appear at top — load in reverse
            for(int _i=saved.Count-1;_i>=0;_i--){var he=saved[_i];historyItems.Insert(0,he);RebuildHistoryItem(he);}
            if(historyItems.Count>0)this.Dispatcher.BeginInvoke(new System.Action(()=>{
                if(statusText!=null)statusText.Text="\u5386\u53f2: "+historyItems.Count+" \u6761";
            }));
        }

        public void LoadCodexConfig() {
            // 1. Try standalone GameDict config first
            string sb2,sk2,sm2,sv2; double fx,fy;
            if(GameDictConfig.Load(out sb2,out sk2,out sm2,out sv2,out fx,out fy)){
                if(!string.IsNullOrEmpty(sb2))apiBase=sb2;
                if(!string.IsNullOrEmpty(sk2))apiKey=sk2;
                if(!string.IsNullOrEmpty(sm2))currentModel=sm2;
                if(sv2!=null)useVision=sv2=="true";
                if(floatingWin!=null&&fx>=0&&fy>=0){floatingWin.LastX=fx;floatingWin.LastY=fy;floatingWin.HasCustomPosition=true;}
                Logger.Info("Loaded from "+GameDictConfig.ConfigPath);
                return;
            }
            // 2. Fallback: read ~/.codex/config.toml
            try {
                string cfgPath=System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),".codex","config.toml");
                if(!File.Exists(cfgPath)) return;
                foreach(string line in File.ReadAllLines(cfgPath)) {
                    string t=line.Trim(); int q1,q2;
                    if(t.StartsWith("model ")||t.StartsWith("model=")) { q1=t.IndexOf('"'); q2=t.LastIndexOf('"'); if(q1>0&&q2>q1) currentModel=t.Substring(q1+1,q2-q1-1); }
                    if(t.StartsWith("experimental_bearer_token")) { q1=t.IndexOf('"'); q2=t.LastIndexOf('"'); if(q1>0&&q2>q1) apiKey=t.Substring(q1+1,q2-q1-1); }
                    if(t.StartsWith("base_url")) { q1=t.IndexOf('"'); q2=t.LastIndexOf('"'); if(q1>0&&q2>q1) { string b=t.Substring(q1+1,q2-q1-1).TrimEnd('/'); if(!b.EndsWith("/v1")) b+="/v1"; apiBase=b+"/chat/completions"; } }
                }
                Logger.Info("Loaded from ~/.codex/config.toml");
            } catch(Exception ex) { Logger.Error("LoadCodexConfig",ex); }
        }
        private void InitUI() {
            this.Title="GameDict AI"; this.Width=480; this.Height=560;
            this.WindowStartupLocation=WindowStartupLocation.CenterScreen;
            this.WindowStyle=WindowStyle.None; this.AllowsTransparency=true;
            this.Background=Brushes.Transparent; this.Topmost=false;

            rootBorder=new Border { CornerRadius=new CornerRadius(12),
                Background=new SolidColorBrush(Color.FromRgb(0,0,0)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(40,255,255,255)),
                BorderThickness=new Thickness(1), Margin=new Thickness(10) };
            rootBorder.Effect=new DropShadowEffect{BlurRadius=18,Color=Colors.Black,Opacity=0.7,ShadowDepth=4,Direction=270};
            rootBorder.MouseLeftButtonDown+=(s,e)=>{ if(e.LeftButton==MouseButtonState.Pressed) try{this.DragMove();}catch{} };

            Grid g=new Grid{Margin=new Thickness(14,10,14,10)};
            g.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
            g.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
            g.RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});
            g.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});

            // Header
            DockPanel header=new DockPanel{LastChildFill=false,Margin=new Thickness(0,0,0,10)};
            StackPanel left=new StackPanel{Orientation=Orientation.Horizontal};
            Border badge=new Border{Width=24,Height=24,CornerRadius=new CornerRadius(6),
                Background=new SolidColorBrush(Color.FromRgb(99,102,241)),Margin=new Thickness(0,0,8,0)};
            badge.Child=new TextBlock{Text="G",Foreground=Brushes.White,FontWeight=FontWeights.Bold,
                HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center,FontSize=12};
            left.Children.Add(badge);
            left.Children.Add(new TextBlock{Text="GameDict AI",FontWeight=FontWeights.SemiBold,FontSize=14,
                Foreground=new SolidColorBrush(Color.FromRgb(230,230,230)),VerticalAlignment=VerticalAlignment.Center});
            DockPanel.SetDock(left,Dock.Left); header.Children.Add(left);

            StackPanel right=new StackPanel{Orientation=Orientation.Horizontal};
            Button setBtn=new Button{Content="Settings",Height=24,Padding=new Thickness(8,0,8,0),
                Background=new SolidColorBrush(Color.FromRgb(20,20,20)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(40,255,255,255)),
                Foreground=new SolidColorBrush(Color.FromRgb(170,170,185)),
                BorderThickness=new Thickness(1),Cursor=Cursors.Hand,Margin=new Thickness(0,0,8,0)};
            setBtn.Click+=(s,e)=>{var d=new SettingsDialog(this);d.Owner=this;d.ShowDialog();};
            right.Children.Add(setBtn);
            Border hkTag=new Border{CornerRadius=new CornerRadius(4),
                Background=new SolidColorBrush(Color.FromArgb(20,99,102,241)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(60,99,102,241)),
                BorderThickness=new Thickness(1),Padding=new Thickness(6,2,6,2),
                Margin=new Thickness(0,0,8,0),VerticalAlignment=VerticalAlignment.Center};
            hkTag.Child=new TextBlock{Text="Alt+Q",FontSize=11,
                FontFamily=new FontFamily("Consolas, Segoe UI Mono"),
                Foreground=new SolidColorBrush(Color.FromRgb(130,130,190))};
            right.Children.Add(hkTag);
            Button closeBtn=new Button{Content="\u2715",Width=26,Height=26,Background=Brushes.Transparent,
                BorderThickness=new Thickness(0),Cursor=Cursors.Hand,
                Foreground=new SolidColorBrush(Color.FromRgb(110,110,125)),FontWeight=FontWeights.Bold};
            closeBtn.Click+=(s,e)=>this.Hide();
            right.Children.Add(closeBtn);
            DockPanel.SetDock(right,Dock.Right); header.Children.Add(right);
            Grid.SetRow(header,0); g.Children.Add(header);

            // Toolbar
            DockPanel toolbar=new DockPanel{LastChildFill=false,Margin=new Thickness(0,0,0,8)};
            Button snipBtn=new Button{Content="\u622a\u5c4f\u67e5\u8bcd  (Ctrl+T)",Height=30,Padding=new Thickness(14,0,14,0),
                Background=new LinearGradientBrush(Color.FromRgb(59,130,246),Color.FromRgb(99,102,241),0),
                Foreground=Brushes.White,FontWeight=FontWeights.SemiBold,
                BorderThickness=new Thickness(0),Cursor=Cursors.Hand,Margin=new Thickness(0,0,8,0)};
            snipBtn.Click+=(s,e)=>TriggerSnipAndAnalyze();
            DockPanel.SetDock(snipBtn,Dock.Left); toolbar.Children.Add(snipBtn);
            Button clearBtn=new Button{Content="\u6e05\u7a7a\u5386\u53f2",Height=30,Padding=new Thickness(12,0,12,0),
                Background=new SolidColorBrush(Color.FromRgb(20,20,20)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(40,255,255,255)),
                Foreground=new SolidColorBrush(Color.FromRgb(190,190,205)),
                BorderThickness=new Thickness(1),Cursor=Cursors.Hand};
            clearBtn.Click+=(s,e)=>{historyItems.Clear();historyList.Items.Clear();statusText.Text="\u5386\u53f2\u5df2\u6e05\u7a7a";HistoryStore.Save(historyItems);};
            DockPanel.SetDock(clearBtn,Dock.Left); toolbar.Children.Add(clearBtn);
            Grid.SetRow(toolbar,1); g.Children.Add(toolbar);

            // History ListBox
            historyList=new ListBox{Background=Brushes.Transparent,BorderThickness=new Thickness(0),
                Padding=new Thickness(0)};
            ScrollViewer.SetHorizontalScrollBarVisibility(historyList,ScrollBarVisibility.Disabled);
            historyList.Resources.Add(SystemColors.HighlightBrushKey,new SolidColorBrush(Color.FromArgb(60,99,102,241)));
            historyList.Resources.Add(SystemColors.HighlightTextBrushKey,new SolidColorBrush(Color.FromRgb(230,230,230)));
            historyList.Resources.Add(SystemColors.InactiveSelectionHighlightBrushKey,new SolidColorBrush(Color.FromArgb(30,99,102,241)));
            historyList.SelectionChanged+=(s,e)=>{
                if(historyList.SelectedIndex<0) return;
                int ri=historyItems.Count-1-historyList.SelectedIndex;
                if(ri<0||ri>=historyItems.Count) return;
                new HistoryDetailWindow(historyItems[ri]){Owner=this}.ShowDialog();
                historyList.SelectedIndex=-1;
            };
            ScrollViewer sv=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto,
                HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};
            sv.Content=historyList;
            Border lb=new Border{CornerRadius=new CornerRadius(8),
                Background=new SolidColorBrush(Color.FromRgb(10,10,10)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(40,255,255,255)),
                BorderThickness=new Thickness(1),Padding=new Thickness(4)};
            lb.Child=sv; Grid.SetRow(lb,2); g.Children.Add(lb);

            // Footer
            DockPanel footer=new DockPanel{LastChildFill=false,Margin=new Thickness(0,8,0,0)};
            statusText=new TextBlock{Text="\u6a21\u578b: "+currentModel,FontSize=11,
                Foreground=new SolidColorBrush(Color.FromRgb(90,90,110))};
            DockPanel.SetDock(statusText,Dock.Left); footer.Children.Add(statusText);
            TextBlock hintTb=new TextBlock{Text="Ctrl+T \u622a\u5c4f  |  \u70b9\u51fb\u6761\u76ee\u67e5\u770b\u8be6\u60c5",
                FontSize=11,Foreground=new SolidColorBrush(Color.FromRgb(90,90,110))};
            DockPanel.SetDock(hintTb,Dock.Right); footer.Children.Add(hintTb);
            Grid.SetRow(footer,3); g.Children.Add(footer);

            rootBorder.Child=g; this.Content=rootBorder;
            this.KeyDown+=(s,e)=>{ if(e.Key==Key.Escape) this.Hide(); };
        }
        private void InitTray() {
            trayIcon=new System.Windows.Forms.NotifyIcon();
            try{byte[] _tb=Convert.FromBase64String(EmbeddedIcon.IcoB64);using(var _tms=new System.IO.MemoryStream(_tb)){trayIcon.Icon=new System.Drawing.Icon(_tms);}}
            catch{trayIcon.Icon=System.Drawing.SystemIcons.Application;}
            trayIcon.Text="GameDict AI"; trayIcon.Visible=true;
            trayIcon.DoubleClick+=(s,e)=>{this.Show();this.Activate();};
            var menu=new System.Windows.Forms.ContextMenuStrip();
            var m1=new System.Windows.Forms.ToolStripMenuItem("\u5386\u53f2\u8bb0\u5f55");
            m1.Click+=(s,e)=>{this.Show();this.Activate();};
            var m2=new System.Windows.Forms.ToolStripMenuItem("\u622a\u5c4f\u67e5\u8bcd (Ctrl+T)");
            m2.Click+=(s,e)=>TriggerSnipAndAnalyze();
            var m3=new System.Windows.Forms.ToolStripMenuItem("Settings");
            m3.Click+=(s,e)=>{this.Show();this.Activate();new SettingsDialog(this){Owner=this}.ShowDialog();};
            var m4=new System.Windows.Forms.ToolStripMenuItem("\u9000\u51fa");
            m4.Click+=(s,e)=>{isRealExit=true;this.Close();};
            menu.Items.AddRange(new System.Windows.Forms.ToolStripItem[]{m1,m2,new System.Windows.Forms.ToolStripSeparator(),m3,new System.Windows.Forms.ToolStripSeparator(),m4});
            trayIcon.ContextMenuStrip=menu;
        }

        private void MainWindow_Loaded(object sender,RoutedEventArgs e) {
            this.Hide();
            windowHandle=new System.Windows.Interop.WindowInteropHelper(this).Handle;
            System.Windows.Interop.HwndSource.FromHwnd(windowHandle).AddHook(HwndHook);
            bool ok2=RegisterHotKey(windowHandle,HOTKEY_ID_ALT_Q,MOD_ALT|MOD_NOREPEAT,VK_Q);
            if(!ok2) ok2=RegisterHotKey(windowHandle,HOTKEY_ID_ALT_Q,MOD_ALT,VK_Q);
            Logger.Info("Alt+Q:"+(ok2?"OK":"FAIL"));
        }

        private bool isRealExit=false;
        private void MainWindow_Closing(object sender,System.ComponentModel.CancelEventArgs e) {
            if(!isRealExit){e.Cancel=true;this.Hide();return;}
            if(trayIcon!=null){trayIcon.Visible=false;trayIcon.Dispose();}
            UnregisterHotKey(windowHandle,HOTKEY_ID_ALT_Q);
            HistoryStore.Save(historyItems);
            Logger.Info("History saved, count="+historyItems.Count);
        }

        private IntPtr HwndHook(IntPtr hwnd,int msg,IntPtr wParam,IntPtr lParam,ref bool handled) {
            if(msg==WM_HOTKEY){int id=wParam.ToInt32();
                if(id==HOTKEY_ID_ALT_Q){Logger.Info("Hotkey id="+id);TriggerSnipAndAnalyze();handled=true;}}
            return IntPtr.Zero;
        }

        public void TriggerSnipAndAnalyze() {
            uint seqBefore=GetClipboardSequenceNumber();
            Logger.Info("Snip seqBefore="+seqBefore);
            try{System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo("ms-screenclip:"){UseShellExecute=true,WindowStyle=System.Diagnostics.ProcessWindowStyle.Hidden,CreateNoWindow=true});Logger.Info("ms-screenclip launched");}
            catch(Exception ex){Logger.Error("Launch failed",ex);}
            Task.Run(()=>{
                for(int i=0;i<80;i++){
                    Thread.Sleep(250);
                    uint seqNow=GetClipboardSequenceNumber();
                    if(seqNow!=seqBefore){
                        Logger.Info("Clipboard changed, waiting 350ms");
                        Thread.Sleep(350);
                        byte[] imgBytes=null;bool hasImg=false;
                        this.Dispatcher.Invoke(()=>{
                            if(Clipboard.ContainsImage()){
                                try{var imgSrc=Clipboard.GetImage();var enc=new System.Windows.Media.Imaging.PngBitmapEncoder();
                                    enc.Frames.Add(System.Windows.Media.Imaging.BitmapFrame.Create(imgSrc));
                                    using(var ms=new MemoryStream()){enc.Save(ms);imgBytes=ms.ToArray();}
                                    hasImg=true;Logger.Info("Captured bytes="+imgBytes.Length);}
                                catch(Exception ex2){Logger.Error("Capture failed",ex2);}
                            }
                        });
                        if(hasImg&&imgBytes!=null){
                            byte[] _ib2=imgBytes;this.Dispatcher.Invoke(()=>{POINT pt;GetCursorPos(out pt);floatingWin.ShowLoading(pt.X,pt.Y,_ib2);});
                            AnalyzeImageForFloating(floatingWin,imgBytes);break;
                        }
                    }
                }
            });
        }
        private void AnalyzeImageForFloating(FloatingResultWindow fw,byte[] imgBytes) {
            bool vis=useVision;
            Task.Run(()=>{
                try{
                    string sysPmt="你是一位顶尖的多语言游戏本地化与攻略私教。请识别并精析截图中出现的内容（支持英语、日语、韩语、德语等全语种）：\\n" +
                        "【中文意思】：结合当前游戏具体画面与语境，给出精准自然、地道的中文翻译；\\n" +
                        "【核心重点】：提炼关键单词/生词/短语，标出读音/原形与在此处游戏场景下的含义及搭配；\\n" +
                        "【游戏大师】：结合星露谷物语等游戏情境，给出1~2条关键背景提示、任务推进要点或下步建议；\\n" +
                        "【顺便学一句】：提取一个最地道、最值得掌握的游戏用语或日常例句。\\n" +
                        "排版要求紧凑干练，层次分明，无需多余套话。";
                    string body;
                    if(vis){
                        string b64=Convert.ToBase64String(imgBytes);
                        string up="请识别并深度解析截图中出现的文字内容，提供精准翻译与词汇语言拆解：";
                        body="{\"model\":\""+currentModel+"\",\"messages\":["+
                            "{\"role\":\"system\",\"content\":\""+sysPmt+"\"},"+
                            "{\"role\":\"user\",\"content\":[{\"type\":\"text\",\"text\":\""+up+"\"},{\"type\":\"image_url\",\"image_url\":{\"url\":\"data:image/png;base64,"+b64+"\"}}]}"+
                            "]}";
                    } else {
                        string ocrText=OcrHelper.ExtractText(imgBytes);
                        Logger.Info("OCR len="+ocrText.Length);
                        if(string.IsNullOrWhiteSpace(ocrText))ocrText="[OCR未识别到文字]";
                        string esc=ocrText.Replace("\\","\\\\").Replace("\"","\\\"").Replace("\n","\\n").Replace("\r","");
                        string up="截图中提取到的文字内容：\\n"+esc+"\\n\\n请分析其所属语种，提供地道中文翻译与核心词汇/语法教学拆解。";
                        body="{\"model\":\""+currentModel+"\",\"messages\":["+
                            "{\"role\":\"system\",\"content\":\""+sysPmt+"\"},"+
                            "{\"role\":\"user\",\"content\":\""+up+"\"}]"+
                            "}";
                    }
                    string result=PostAI(body);
                    Logger.Info("AI chars="+result.Length);
                    byte[] _ib3=imgBytes;string _r3=result;this.Dispatcher.Invoke(()=>{fw.ShowResult(_r3);AddHistory("截图","[截图查词]",_r3,_ib3);});
                }catch(Exception ex){Logger.Error("AnalyzeFloating",ex);this.Dispatcher.Invoke(()=>fw.ShowResult("解析失败: "+ex.Message));}
            });
        }

        private string PostAI(string jsonBody) {
            var req=(HttpWebRequest)WebRequest.Create(apiBase);
            req.Method="POST";req.ContentType="application/json";
            req.Headers["Authorization"]="Bearer "+apiKey;
            req.UserAgent="Codex/1.0";req.Timeout=60000;
            Logger.Info("PostAI body_len="+jsonBody.Length+" model="+currentModel+" base="+apiBase);
            byte[] data=new UTF8Encoding(false).GetBytes(jsonBody);
            req.ContentLength=data.Length;
            using(Stream st=req.GetRequestStream()) st.Write(data,0,data.Length);
            try{
                using(var resp=(HttpWebResponse)req.GetResponse())
                using(var rdr=new StreamReader(resp.GetResponseStream(),Encoding.UTF8))
                    return ExtractContent(rdr.ReadToEnd());
            }catch(WebException wex){
                string errBody="";
                if(wex.Response!=null){
                    using(var er=new StreamReader(wex.Response.GetResponseStream(),Encoding.UTF8))
                        errBody=er.ReadToEnd();
                }
                Logger.Error("PostAI HTTP error body="+errBody,wex);
                throw;
            }
        }

        private string ExtractContent(string json) {
            try{
                int ci=json.IndexOf("\"content\":");if(ci<0) return json;
                int q1=json.IndexOf('"',ci+10);if(q1<0) return json;
                var sb=new StringBuilder();
                for(int i=q1+1;i<json.Length;i++){
                    char c=json[i];
                    if(c=='\\'&&i+1<json.Length){char n=json[i+1];
                        if(n=='n'){sb.Append('\n');i++;}else if(n=='t'){sb.Append('\t');i++;}
                        else if(n=='"'){sb.Append('"');i++;}else if(n=='\\'){sb.Append('\\');i++;}
                        else sb.Append(c);
                    }else if(c=='"') break; else sb.Append(c);
                }
                return sb.ToString();
            }catch{return json;}
        }

        private void RebuildHistoryItem(HistoryEntry entry){
            // Called during load (oldest-first after reversal); appends to bottom
            // Insert date header if this is the first entry for this date in the list
            bool hdrExists=false;
            foreach(System.Windows.Controls.ListBoxItem it in historyList.Items){
                var hb=it.Content as Border;
                if(hb!=null){var tb=hb.Child as TextBlock;
                    if(tb!=null&&tb.Foreground is SolidColorBrush){
                        string label=entry.Date==DateTime.Now.ToString("yyyy-MM-dd")?"\u4eca\u5929":
                            entry.Date==DateTime.Now.AddDays(-1).ToString("yyyy-MM-dd")?"\u6628\u5929":entry.Date;
                        if(tb.Text==label){hdrExists=true;break;}
                    }
                }
            }
            if(!hdrExists)historyList.Items.Add(MakeDateHeader(entry.Date??""));
            historyList.Items.Add(MakeCard(entry));
        }
        private void AddHistory(string source,string query,string result,byte[] imgBytes=null) {
            string today=DateTime.Now.ToString("yyyy-MM-dd");
            string imgPath=null;
            if(imgBytes!=null&&imgBytes.Length>0)imgPath=HistoryStore.SaveImage(imgBytes);
            var entry=new HistoryEntry{
                Date=today,Time=DateTime.Now.ToString("HH:mm:ss"),Source=source,
                Query=query.Length>40?query.Substring(0,40)+"...":query,
                Result=result,ImagePath=imgPath};
            historyItems.Add(entry);
            // Date group header if needed
            bool needHeader=true;
            foreach(var it in historyItems){if(it!=entry&&it.Date==today){needHeader=false;break;}}
            if(needHeader)historyList.Items.Insert(0,MakeDateHeader(today));
            historyList.Items.Insert(needHeader?1:0,MakeCard(entry));
            statusText.Text="\u5386\u53f2: "+historyItems.Count+" \u6761";
        }
        private ListBoxItem MakeDateHeader(string date){
            string label=date==DateTime.Now.ToString("yyyy-MM-dd")?"\u4eca\u5929":
                date==DateTime.Now.AddDays(-1).ToString("yyyy-MM-dd")?"\u6628\u5929":date;
            Border hb=new Border{
                Padding=new Thickness(8,4,8,4),Margin=new Thickness(0,6,0,2),
                BorderBrush=new SolidColorBrush(Color.FromArgb(40,255,255,255)),
                BorderThickness=new Thickness(0,0,0,1)};
            hb.Child=new TextBlock{Text=label,FontSize=11,FontWeight=FontWeights.SemiBold,
                Foreground=new SolidColorBrush(Color.FromRgb(99,102,241))};
            return new ListBoxItem{Content=hb,Background=Brushes.Transparent,
                Padding=new Thickness(0),IsEnabled=false,
                HorizontalContentAlignment=HorizontalAlignment.Stretch};
        }
        private ListBoxItem MakeCard(HistoryEntry entry){
            Border card=new Border{CornerRadius=new CornerRadius(6),
                Background=new SolidColorBrush(Color.FromRgb(16,16,16)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(35,255,255,255)),
                BorderThickness=new Thickness(1),Padding=new Thickness(10,8,10,8),Margin=new Thickness(2,2,2,4)};
            Grid cg=new Grid();
            cg.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto}); // thumb
            cg.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(1,GridUnitType.Star)});
            cg.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
            cg.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
            cg.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
            // thumbnail
            if(!string.IsNullOrEmpty(entry.ImagePath)&&File.Exists(entry.ImagePath)){
                try{
                    var bmp=new System.Windows.Media.Imaging.BitmapImage();
                    bmp.BeginInit();bmp.UriSource=new Uri(entry.ImagePath);
                    bmp.DecodePixelHeight=54;
                    bmp.CacheOption=System.Windows.Media.Imaging.BitmapCacheOption.OnLoad;
                    bmp.EndInit();bmp.Freeze();
                    var img=new System.Windows.Controls.Image{Source=bmp,Width=80,Height=54,
                        Stretch=System.Windows.Media.Stretch.UniformToFill,
                        VerticalAlignment=VerticalAlignment.Top,Margin=new Thickness(0,0,10,0)};
                    Border imgBrd=new Border{CornerRadius=new CornerRadius(4),ClipToBounds=true,
                        Width=80,Height=54,Margin=new Thickness(0,0,10,0),VerticalAlignment=VerticalAlignment.Top};
                    imgBrd.Child=img;
                    Grid.SetRow(imgBrd,0);Grid.SetColumn(imgBrd,0);Grid.SetRowSpan(imgBrd,3);
                    cg.Children.Add(imgBrd);
                }catch{}
            }
            // source badge + query
            StackPanel topRow=new StackPanel{Orientation=Orientation.Horizontal};
            Border srcB=new Border{CornerRadius=new CornerRadius(3),
                Background=new SolidColorBrush(Color.FromArgb(40,99,102,241)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(80,99,102,241)),
                BorderThickness=new Thickness(1),Padding=new Thickness(5,1,5,1),Margin=new Thickness(0,1,8,0)};
            srcB.Child=new TextBlock{Text=entry.Source,FontSize=10,Foreground=new SolidColorBrush(Color.FromRgb(130,130,190))};
            topRow.Children.Add(srcB);
            topRow.Children.Add(new TextBlock{Text=entry.Query,FontSize=12,FontWeight=FontWeights.SemiBold,
                Foreground=new SolidColorBrush(Color.FromRgb(220,220,232)),
                TextTrimming=TextTrimming.CharacterEllipsis,VerticalAlignment=VerticalAlignment.Center});
            Grid.SetRow(topRow,0);Grid.SetColumn(topRow,1);cg.Children.Add(topRow);
            // time
            TextBlock timeTb=new TextBlock{Text=entry.Time,FontSize=10,
                Foreground=new SolidColorBrush(Color.FromRgb(80,80,110)),Margin=new Thickness(0,3,0,2)};
            Grid.SetRow(timeTb,1);Grid.SetColumn(timeTb,1);cg.Children.Add(timeTb);
            // preview
            string preview=(entry.Result??"").Replace("\n"," ").Replace("\r","");
            if(preview.Length>60)preview=preview.Substring(0,60)+"...";
            TextBlock pTb=new TextBlock{Text=preview,FontSize=11,
                Foreground=new SolidColorBrush(Color.FromRgb(100,100,118)),
                TextWrapping=TextWrapping.NoWrap,TextTrimming=TextTrimming.CharacterEllipsis};
            Grid.SetRow(pTb,2);Grid.SetColumn(pTb,1);cg.Children.Add(pTb);
            card.Child=cg;
            return new ListBoxItem{Content=card,Background=Brushes.Transparent,
                Padding=new Thickness(0),HorizontalContentAlignment=HorizontalAlignment.Stretch};
        }
    }
    public static class HistoryStore {
        private static readonly string HistoryPath=System.IO.Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"GameDict","history.dat");
        public  static readonly string ImagesDir=System.IO.Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"GameDict","images");
        private const string SEP="---ENTRY---";
        public static string SaveImage(byte[] bytes){
            try{
                Directory.CreateDirectory(ImagesDir);
                string path=System.IO.Path.Combine(ImagesDir,DateTime.Now.ToString("yyyyMMdd_HHmmss_fff")+".png");
                File.WriteAllBytes(path,bytes); return path;
            }catch(Exception ex){Logger.Error("SaveImage",ex);return null;}
        }
        public static void Save(List<HistoryEntry> items){
            try{
                Directory.CreateDirectory(System.IO.Path.GetDirectoryName(HistoryPath));
                var sb=new System.Text.StringBuilder();
                foreach(var e in items){
                    sb.AppendLine(SEP);
                    sb.AppendLine(e.Date??"");
                    sb.AppendLine(e.Time??"");
                    sb.AppendLine(e.Source??"");
                    sb.AppendLine((e.Query??"").Replace("\n","\\n").Replace("\r",""));
                    sb.AppendLine((e.Result??"").Replace("\n","\\n").Replace("\r",""));
                    sb.AppendLine(e.ImagePath??"");
                }
                File.WriteAllText(HistoryPath,sb.ToString(),System.Text.Encoding.UTF8);
            }catch(Exception ex){Logger.Error("HistoryStore.Save",ex);}
        }
        public static List<HistoryEntry> Load(){
            var list=new List<HistoryEntry>();
            try{
                if(!File.Exists(HistoryPath))return list;
                string[] lines=File.ReadAllLines(HistoryPath,System.Text.Encoding.UTF8);
                int i=0;
                while(i<lines.Length){
                    if(lines[i].Trim()==SEP){
                        // New 7-line format: SEP date time source query result imagepath
                        if(i+6<lines.Length&&lines[i+2].Length==8&&lines[i+2].Contains(":")){
                            // date is yyyy-MM-dd (10 chars), time HH:mm:ss (8 chars)
                        }
                        // Detect format by checking if field at i+1 looks like a date
                        bool newFmt=i+6<lines.Length&&lines[i+1].Length==10&&lines[i+1].Contains("-");
                        if(newFmt&&i+6<lines.Length){
                            var entry=new HistoryEntry{
                                Date=lines[i+1],Time=lines[i+2],Source=lines[i+3],
                                Query=lines[i+4].Replace("\\n","\n"),
                                Result=lines[i+5].Replace("\\n","\n"),
                                ImagePath=lines[i+6].Trim()};
                            if(!File.Exists(entry.ImagePath))entry.ImagePath=null;
                            list.Add(entry);i+=7;continue;
                        } else if(i+4<lines.Length){
                            // Old 5-line: SEP time source query result
                            var entry=new HistoryEntry{
                                Date=DateTime.Now.ToString("yyyy-MM-dd"),
                                Time=lines[i+1],Source=lines[i+2],
                                Query=lines[i+3].Replace("\\n","\n"),
                                Result=lines[i+4].Replace("\\n","\n"),
                                ImagePath=null};
                            list.Add(entry);i+=5;continue;
                        }
                    }
                    i++;
                }
            }catch(Exception ex){Logger.Error("HistoryStore.Load",ex);}
            return list;
        }
    }

    public class HistoryEntry {
        public string Date{get;set;}      // yyyy-MM-dd
        public string Time{get;set;}
        public string Source{get;set;}
        public string Query{get;set;}
        public string Result{get;set;}
        public string ImagePath{get;set;} // path to saved screenshot, or empty
    }

    public class HistoryDetailWindow : Window {
        public HistoryDetailWindow(HistoryEntry entry) {
            this.Title="GameDict - \u8be6\u60c5"; this.Width=520; this.Height=520;
            this.WindowStartupLocation=WindowStartupLocation.CenterOwner;
            this.Background=new SolidColorBrush(Color.FromRgb(8,8,8));
            Grid g=new Grid{Margin=new Thickness(16)};
            g.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
            g.RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});
            g.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
            DockPanel h=new DockPanel{LastChildFill=false,Margin=new Thickness(0,0,0,10)};
            StackPanel hi=new StackPanel{Orientation=Orientation.Horizontal};
            Border sb2=new Border{CornerRadius=new CornerRadius(3),
                Background=new SolidColorBrush(Color.FromArgb(40,99,102,241)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(80,99,102,241)),
                BorderThickness=new Thickness(1),Padding=new Thickness(6,2,6,2),Margin=new Thickness(0,0,8,0)};
            sb2.Child=new TextBlock{Text=entry.Source,FontSize=11,Foreground=new SolidColorBrush(Color.FromRgb(130,130,190))};
            hi.Children.Add(sb2);
            hi.Children.Add(new TextBlock{Text=entry.Time+"  "+entry.Query,FontSize=13,
                FontWeight=FontWeights.SemiBold,Foreground=new SolidColorBrush(Color.FromRgb(220,220,232)),
                VerticalAlignment=VerticalAlignment.Center});
            DockPanel.SetDock(hi,Dock.Left); h.Children.Add(hi);
            Button cb=new Button{Content="\u2715",Width=26,Height=26,Background=Brushes.Transparent,
                BorderThickness=new Thickness(0),Cursor=Cursors.Hand,
                Foreground=new SolidColorBrush(Color.FromRgb(110,110,125)),FontWeight=FontWeights.Bold};
            cb.Click+=(s,e)=>this.Close();
            DockPanel.SetDock(cb,Dock.Right); h.Children.Add(cb);
            Grid.SetRow(h,0); g.Children.Add(h);
            // Image preview
            if(!string.IsNullOrEmpty(entry.ImagePath)&&File.Exists(entry.ImagePath)){
                try{
                    g.RowDefinitions.Insert(1,new RowDefinition{Height=GridLength.Auto});
                    // shift existing row indices
                    var bmp=new System.Windows.Media.Imaging.BitmapImage(new Uri(entry.ImagePath));
                    var img=new System.Windows.Controls.Image{Source=bmp,MaxHeight=140,
                        Stretch=System.Windows.Media.Stretch.Uniform,HorizontalAlignment=HorizontalAlignment.Left};
                    Border imgBrd=new Border{CornerRadius=new CornerRadius(6),ClipToBounds=true,
                        BorderBrush=new SolidColorBrush(Color.FromArgb(50,255,255,255)),
                        BorderThickness=new Thickness(1),Margin=new Thickness(0,0,0,10)};
                    imgBrd.Child=img;
                    Grid.SetRow(imgBrd,1); g.Children.Add(imgBrd);
                    // Move result/copy to row+1
                    Grid.SetRow(g.Children[1],0); // header stays 0
                }catch{}
            }
            ScrollViewer sv=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto};
            sv.Content=new TextBlock{Text=entry.Result,FontSize=13,LineHeight=22,TextWrapping=TextWrapping.Wrap,
                Foreground=new SolidColorBrush(Color.FromRgb(210,210,222)),
                FontFamily=new FontFamily("Segoe UI Variable Text, Segoe UI, Microsoft YaHei")};
            Border cb3=new Border{CornerRadius=new CornerRadius(8),
                Background=new SolidColorBrush(Color.FromRgb(14,14,14)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(40,255,255,255)),
                BorderThickness=new Thickness(1),Padding=new Thickness(14)};
            cb3.Child=sv; Grid.SetRow(cb3,g.RowDefinitions.Count-2); g.Children.Add(cb3);
            Button copyBtn=new Button{Content="\u590d\u5236\u5185\u5bb9",Height=30,Padding=new Thickness(16,0,16,0),
                Background=new SolidColorBrush(Color.FromRgb(20,20,20)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(40,255,255,255)),
                BorderThickness=new Thickness(1),Foreground=new SolidColorBrush(Color.FromRgb(180,180,195)),
                Cursor=Cursors.Hand,Margin=new Thickness(0,10,0,0),HorizontalAlignment=HorizontalAlignment.Left};
            copyBtn.Click+=(s,e)=>{try{Clipboard.SetText(entry.Result);copyBtn.Content="\u5df2\u590d\u5236";}catch{}};
            Grid.SetRow(copyBtn,2); g.Children.Add(copyBtn);
            this.Content=g;
            this.KeyDown+=(s,e)=>{if(e.Key==Key.Escape)this.Close();};
        }
    }

    public class SettingsDialog : Window {
        private TextBox TB,TK,CMBTEXT; private System.Windows.Controls.Primitives.Popup CMBPOPUP; private ListBox CMBLB; private MainWindow M;
        public SettingsDialog(MainWindow main) {
            M=main; this.Title="设置"; this.Width=440; this.Height=380;
            this.WindowStartupLocation=WindowStartupLocation.CenterOwner;
            this.Background=new SolidColorBrush(Color.FromRgb(0,0,0));
            // Global dark button style for this window
            var btnStyle=new Style(typeof(Button));
            btnStyle.Setters.Add(new Setter(Button.BackgroundProperty,new SolidColorBrush(Color.FromRgb(30,30,40))));
            btnStyle.Setters.Add(new Setter(Button.ForegroundProperty,new SolidColorBrush(Color.FromRgb(200,200,215))));
            btnStyle.Setters.Add(new Setter(Button.BorderThicknessProperty,new Thickness(1)));
            btnStyle.Setters.Add(new Setter(Button.BorderBrushProperty,new SolidColorBrush(Color.FromArgb(50,255,255,255))));
            btnStyle.Setters.Add(new Setter(Button.CursorProperty,Cursors.Hand));
            btnStyle.Setters.Add(new Setter(Button.TemplateProperty,(ControlTemplate)System.Windows.Markup.XamlReader.Parse(
                "<ControlTemplate xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\" TargetType=\"Button\">" +
                "  <Border Name=\"bd\" Background=\"{TemplateBinding Background}\" BorderBrush=\"{TemplateBinding BorderBrush}\" BorderThickness=\"{TemplateBinding BorderThickness}\" Padding=\"{TemplateBinding Padding}\">" +
                "    <ContentPresenter HorizontalAlignment=\"Center\" VerticalAlignment=\"Center\"/>" +
                "  </Border>" +
                "  <ControlTemplate.Triggers>" +
                "    <Trigger Property=\"IsMouseOver\" Value=\"True\"><Setter TargetName=\"bd\" Property=\"Background\" Value=\"#FF2A2A3A\"/></Trigger>" +
                "    <Trigger Property=\"IsPressed\" Value=\"True\"><Setter TargetName=\"bd\" Property=\"Background\" Value=\"#FF1A1A28\"/></Trigger>" +
                "    <Trigger Property=\"IsEnabled\" Value=\"False\"><Setter TargetName=\"bd\" Property=\"Opacity\" Value=\"0.4\"/></Trigger>" +
                "  </ControlTemplate.Triggers>" +
                "</ControlTemplate>")));
            this.Resources[typeof(Button)]=btnStyle;
            StackPanel sp=new StackPanel{Margin=new Thickness(20)};
            DockPanel hd=new DockPanel{LastChildFill=false,Margin=new Thickness(0,0,0,12)};
            hd.Children.Add(new TextBlock{Text="设置",FontSize=16,FontWeight=FontWeights.SemiBold,
                Foreground=new SolidColorBrush(Color.FromRgb(220,220,230))});
            sp.Children.Add(hd);
            sp.Children.Add(new TextBlock{Text="配置文件: "+GameDictConfig.ConfigPath,FontSize=10,
                Foreground=new SolidColorBrush(Color.FromRgb(80,80,100)),
                Margin=new Thickness(0,0,0,12),TextWrapping=TextWrapping.Wrap});
            sp.Children.Add(Lbl("API 地址")); TB=Inp(M.apiBase); sp.Children.Add(TB);
            sp.Children.Add(Lbl("API 密鑰")); TK=Inp(M.apiKey);  sp.Children.Add(TK);
            // Model row: custom TextBox + Popup + ListBox
            sp.Children.Add(Lbl("模型"));
            DockPanel modelRow=new DockPanel{LastChildFill=true,Margin=new Thickness(0,0,0,10)};
            Button fetchBtn=new Button{Content="获取",Width=48,Height=28,Cursor=Cursors.Hand,
                Background=new SolidColorBrush(Color.FromRgb(40,40,55)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(60,99,102,241)),
                BorderThickness=new Thickness(1),Margin=new Thickness(6,0,0,0),
                Foreground=new SolidColorBrush(Color.FromRgb(160,165,220))};
            DockPanel.SetDock(fetchBtn,Dock.Right); modelRow.Children.Add(fetchBtn);
            Grid cmbGrid=new Grid{Height=28};
            cmbGrid.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(1,GridUnitType.Star)});
            cmbGrid.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});
            CMBTEXT=new TextBox{
                Background=new SolidColorBrush(Color.FromRgb(16,16,16)),
                Foreground=new SolidColorBrush(Color.FromRgb(215,215,225)),
                CaretBrush=new SolidColorBrush(Color.FromRgb(215,215,225)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(40,255,255,255)),
                BorderThickness=new Thickness(1,1,0,1),
                VerticalContentAlignment=VerticalAlignment.Center,
                Padding=new Thickness(8,0,4,0),Text=M.currentModel};
            Grid.SetColumn(CMBTEXT,0); cmbGrid.Children.Add(CMBTEXT);
            Button arrowBtn=new Button{Content="▾",Width=22,
                Background=new SolidColorBrush(Color.FromRgb(16,16,16)),
                Foreground=new SolidColorBrush(Color.FromRgb(160,160,180)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(40,255,255,255)),
                BorderThickness=new Thickness(0,1,1,1),Cursor=Cursors.Hand};
            Grid.SetColumn(arrowBtn,1); cmbGrid.Children.Add(arrowBtn);
            modelRow.Children.Add(cmbGrid);
            sp.Children.Add(modelRow);
            CMBLB=new ListBox{
                Background=new SolidColorBrush(Color.FromRgb(16,16,16)),
                Foreground=new SolidColorBrush(Color.FromRgb(215,215,225)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(60,255,255,255)),
                BorderThickness=new Thickness(1),MaxHeight=200};
            ScrollViewer.SetVerticalScrollBarVisibility(CMBLB,ScrollBarVisibility.Auto);
            var lbItemStyle=new Style(typeof(ListBoxItem));
            lbItemStyle.Setters.Add(new Setter(ListBoxItem.BackgroundProperty,new SolidColorBrush(Color.FromRgb(16,16,16))));
            lbItemStyle.Setters.Add(new Setter(ListBoxItem.ForegroundProperty,new SolidColorBrush(Color.FromRgb(215,215,225))));
            lbItemStyle.Setters.Add(new Setter(ListBoxItem.PaddingProperty,new Thickness(10,5,10,5)));
            var lbHover=new Trigger{Property=ListBoxItem.IsMouseOverProperty,Value=true};
            lbHover.Setters.Add(new Setter(ListBoxItem.BackgroundProperty,new SolidColorBrush(Color.FromRgb(40,40,55))));
            lbItemStyle.Triggers.Add(lbHover);
            var lbSel=new Trigger{Property=ListBoxItem.IsSelectedProperty,Value=true};
            lbSel.Setters.Add(new Setter(ListBoxItem.BackgroundProperty,new SolidColorBrush(Color.FromRgb(55,60,100))));
            lbItemStyle.Triggers.Add(lbSel);
            CMBLB.ItemContainerStyle=lbItemStyle;
            CMBPOPUP=new System.Windows.Controls.Primitives.Popup{
                Child=CMBLB,StaysOpen=false,AllowsTransparency=true,
                PlacementTarget=cmbGrid,Placement=System.Windows.Controls.Primitives.PlacementMode.Bottom};
            CMBLB.SelectionChanged+=(s,e)=>{
                if(CMBLB.SelectedItem!=null){CMBTEXT.Text=CMBLB.SelectedItem.ToString();}
                CMBPOPUP.IsOpen=false;
            };
            System.Action togglePopup=()=>{
                CMBPOPUP.Width=cmbGrid.ActualWidth+arrowBtn.ActualWidth;
                CMBPOPUP.IsOpen=!CMBPOPUP.IsOpen;
            };
            arrowBtn.Click+=(s,e)=>togglePopup();
            CMBTEXT.PreviewKeyDown+=(s,e)=>{
                if(e.Key==Key.Down||e.Key==Key.F4){togglePopup();e.Handled=true;}
            };
            fetchBtn.Click+=(s,e)=>{
                fetchBtn.Content="…"; fetchBtn.IsEnabled=false;
                string baseUrl=TB.Text.Trim(); string key=TK.Text.Trim();
                string modelsUrl=baseUrl;
                if(modelsUrl.EndsWith("/chat/completions"))modelsUrl=modelsUrl.Substring(0,modelsUrl.Length-17)+"/models";
                else if(!modelsUrl.EndsWith("/models"))modelsUrl=modelsUrl.TrimEnd('/')+"/models";
                System.Threading.Tasks.Task.Run(()=>{
                    var ids=new System.Collections.Generic.List<string>();
                    try{
                        var req=(System.Net.HttpWebRequest)System.Net.WebRequest.Create(modelsUrl);
                        req.Method="GET"; req.Timeout=8000;
                        req.Headers["Authorization"]="Bearer "+key;
                        req.ContentType="application/json";
                        using(var resp=(System.Net.HttpWebResponse)req.GetResponse())
                        using(var sr2=new System.IO.StreamReader(resp.GetResponseStream())){
                            string json=sr2.ReadToEnd();
                            int pos=0;
                            while(true){
                                int idx2=json.IndexOf("\"id\"",pos);
                                if(idx2<0)break;
                                int q1=json.IndexOf('"',idx2+4);
                                if(q1<0)break;
                                int q2=json.IndexOf('"',q1+1);
                                if(q2<0)break;
                                string id=json.Substring(q1+1,q2-q1-1);
                                if(id.Length>0&&!id.Contains("/")&&id.IndexOf("codex",System.StringComparison.OrdinalIgnoreCase)<0)ids.Add(id);
                                pos=q2+1;
                            }
                            ids.Sort();
                        }
                    }catch(Exception ex){Logger.Error("FetchModels",ex);}
                    this.Dispatcher.Invoke(()=>{
                        fetchBtn.Content="获取"; fetchBtn.IsEnabled=true;
                        if(ids.Count>0){
                            string cur=CMBTEXT.Text;
                            CMBLB.Items.Clear();
                            foreach(var id in ids)CMBLB.Items.Add(id);
                            CMBTEXT.Text=cur;
                            CMBPOPUP.Width=cmbGrid.ActualWidth+arrowBtn.ActualWidth;
                            CMBPOPUP.IsOpen=true;
                        }
                    });
                });
            };
            // Vision toggle
            DockPanel vtRow=new DockPanel{LastChildFill=false,Margin=new Thickness(0,0,0,12)};
            CheckBox visionChk=new CheckBox{
                Content="图像模式（直接传图）",IsChecked=M.useVision,
                Foreground=new SolidColorBrush(Color.FromRgb(190,190,210)),
                VerticalContentAlignment=VerticalAlignment.Center};
            TextBlock visionHint=new TextBlock{
                Text="取消勾选则先 OCR 再传文字，适合纯文本模型",
                FontSize=10,Foreground=new SolidColorBrush(Color.FromRgb(90,90,115)),
                Margin=new Thickness(8,0,0,0),VerticalAlignment=VerticalAlignment.Center};
            DockPanel.SetDock(visionChk,Dock.Left); vtRow.Children.Add(visionChk);
            vtRow.Children.Add(visionHint);
            sp.Children.Add(vtRow);
            // Actions
            StackPanel btns=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};
            Button save=new Button{Content="保存",Width=70,Height=28,
                Background=new SolidColorBrush(Color.FromRgb(99,102,241)),Foreground=Brushes.White,
                FontWeight=FontWeights.SemiBold,BorderThickness=new Thickness(0),Cursor=Cursors.Hand,
                Margin=new Thickness(0,0,8,0)};
            save.Click+=(s,e)=>{M.apiBase=TB.Text.Trim();M.apiKey=TK.Text.Trim();M.currentModel=CMBTEXT.Text.Trim();M.useVision=visionChk.IsChecked==true;
                double sx=M.floatingWin!=null&&M.floatingWin.HasCustomPosition?M.floatingWin.LastX:-1;double sy=M.floatingWin!=null&&M.floatingWin.HasCustomPosition?M.floatingWin.LastY:-1;GameDictConfig.Save(M.apiBase,M.apiKey,M.currentModel,M.useVision,sx,sy);this.Close();};
            Button cancel=new Button{Content="取消",Width=60,Height=28,
                Background=new SolidColorBrush(Color.FromRgb(20,20,20)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(40,255,255,255)),
                BorderThickness=new Thickness(1),Foreground=new SolidColorBrush(Color.FromRgb(180,180,195)),Cursor=Cursors.Hand};
            cancel.Click+=(s,e)=>this.Close();
            btns.Children.Add(save); btns.Children.Add(cancel); sp.Children.Add(btns);
            var sv=new System.Windows.Controls.ScrollViewer{VerticalScrollBarVisibility=System.Windows.Controls.ScrollBarVisibility.Auto,Content=sp};
            this.Content=sv;
            this.SourceInitialized+=(s,e)=>ApplyDarkTitleBar();
        }
        [System.Runtime.InteropServices.DllImport("dwmapi.dll")]
        private static extern int DwmSetWindowAttribute(IntPtr hwnd,int attr,ref int attrValue,int attrSize);
        private void ApplyDarkTitleBar(){
            try{
                var hwnd=new System.Windows.Interop.WindowInteropHelper(this).Handle;
                int dark=1;
                DwmSetWindowAttribute(hwnd,20,ref dark,sizeof(int)); // DWMWA_USE_IMMERSIVE_DARK_MODE
            }catch{}
        }
        private TextBlock Lbl(string t) {
            return new TextBlock{Text=t,FontSize=11,Margin=new Thickness(0,0,0,4),
                Foreground=new SolidColorBrush(Color.FromRgb(130,130,150))};
        }
        private TextBox Inp(string v) {
            return new TextBox{Text=v,Height=28,Margin=new Thickness(0,0,0,10),
                VerticalContentAlignment=VerticalAlignment.Center,Padding=new Thickness(8,0,8,0),
                Background=new SolidColorBrush(Color.FromRgb(16,16,16)),
                Foreground=new SolidColorBrush(Color.FromRgb(215,215,225)),
                CaretBrush=new SolidColorBrush(Color.FromRgb(215,215,225)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(40,255,255,255)),BorderThickness=new Thickness(1)};
        }

    }

    public class FloatingResultWindow : Window {
        private RichTextBox contentBox;
        private System.Windows.Controls.Image previewImg;
        private Border previewBorder;
        public double LastX = -1;
        public double LastY = -1;
        public bool HasCustomPosition = false;
        public FloatingResultWindow() {
            this.Title="GameDict Float"; this.Width=420; this.Height=520;
            this.WindowStyle=WindowStyle.None; this.AllowsTransparency=true;
            this.Background=Brushes.Transparent; this.Topmost=true;
            this.ShowInTaskbar=false; this.ResizeMode=ResizeMode.NoResize;
            Border root=new Border{CornerRadius=new CornerRadius(12),
                Background=new SolidColorBrush(Color.FromArgb(170,12,12,16)),
                BorderBrush=new SolidColorBrush(Color.FromArgb(40,255,255,255)),
                BorderThickness=new Thickness(1),Margin=new Thickness(8)};
            root.Effect=new DropShadowEffect{BlurRadius=22,Color=Colors.Black,Opacity=0.55,ShadowDepth=4,Direction=270};
            root.MouseLeftButtonDown+=(s,e)=>{
                if(e.LeftButton==MouseButtonState.Pressed){
                    try{
                        this.DragMove();
                        LastX=this.Left; LastY=this.Top; HasCustomPosition=true;
                        GameDictConfig.SavePosition(LastX,LastY);
                    }catch{}
                }
            };
            Grid g=new Grid{Margin=new Thickness(12,10,12,10)};
            g.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
            g.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
            g.RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});
            g.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
            // Header
            DockPanel h=new DockPanel{LastChildFill=false,Margin=new Thickness(0,0,0,8)};
            Border bg=new Border{Width=18,Height=18,CornerRadius=new CornerRadius(4),
                Background=new SolidColorBrush(Color.FromRgb(99,102,241)),VerticalAlignment=VerticalAlignment.Center};
            bg.Child=new TextBlock{Text="G",Foreground=Brushes.White,FontSize=10,FontWeight=FontWeights.Bold,
                HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};
            DockPanel.SetDock(bg,Dock.Left); h.Children.Add(bg);
            Button close=new Button{Content="\u2715",Width=26,Height=26,
                Background=new SolidColorBrush(Color.FromArgb(40,255,255,255)),
                BorderThickness=new Thickness(0),Cursor=Cursors.Hand,
                Foreground=new SolidColorBrush(Color.FromRgb(190,190,205)),FontWeight=FontWeights.Bold};
            close.MouseEnter+=(s,e)=>close.Background=new SolidColorBrush(Color.FromRgb(180,30,30));
            close.MouseLeave+=(s,e)=>close.Background=new SolidColorBrush(Color.FromArgb(40,255,255,255));
            close.Click+=(s,e)=>this.Hide();
            DockPanel.SetDock(close,Dock.Right); h.Children.Add(close);
            Grid.SetRow(h,0); g.Children.Add(h);
            // Preview thumbnail
            previewImg=new System.Windows.Controls.Image{
                MaxHeight=100,Stretch=System.Windows.Media.Stretch.Uniform,
                HorizontalAlignment=HorizontalAlignment.Left};
            previewBorder=new Border{CornerRadius=new CornerRadius(6),
                BorderBrush=new SolidColorBrush(Color.FromArgb(50,255,255,255)),
                BorderThickness=new Thickness(1),Padding=new Thickness(2),
                Margin=new Thickness(0,0,0,8),Visibility=Visibility.Collapsed};
            previewBorder.Child=previewImg;
            Grid.SetRow(previewBorder,1); g.Children.Add(previewBorder);
            // Content
            contentBox=new RichTextBox{Background=Brushes.Transparent,
                BorderThickness=new Thickness(0),IsReadOnly=true,
                Foreground=new SolidColorBrush(Color.FromRgb(200,200,215)),
                FontSize=13,FontFamily=new FontFamily("Segoe UI Variable Text, Segoe UI, Microsoft YaHei"),
                Padding=new Thickness(2)};
            ScrollViewer.SetVerticalScrollBarVisibility(contentBox,ScrollBarVisibility.Auto);
            ScrollViewer.SetHorizontalScrollBarVisibility(contentBox,ScrollBarVisibility.Disabled);
            Border cc=new Border{CornerRadius=new CornerRadius(8),
                Background=new SolidColorBrush(Color.FromArgb(20,0,0,0)),Padding=new Thickness(4,2,4,2)};
            cc.Child=contentBox; Grid.SetRow(cc,2); g.Children.Add(cc);
            // Footer removed per user request
            root.Child=g; this.Content=root;
            this.KeyDown+=(s,e)=>{if(e.Key==Key.Escape)this.Hide();};
        }
        public void ShowLoading(double cursorX,double cursorY,byte[] imgBytes){
            this.WindowState=WindowState.Normal; this.Width=420; this.Height=520;
            if(HasCustomPosition&&LastX>=0&&LastY>=0){
                // 使用上一次拖拽记住的位置
                EnsureWithinScreen(LastX,LastY);
            }else{
                // 首次未拖拽过时，跟随鼠标附近弹出
                PositionAt(cursorX,cursorY);
            }
            if(imgBytes!=null&&imgBytes.Length>0){
                try{
                    var bmp=new System.Windows.Media.Imaging.BitmapImage();
                    bmp.BeginInit();
                    bmp.StreamSource=new MemoryStream(imgBytes);
                    bmp.CacheOption=System.Windows.Media.Imaging.BitmapCacheOption.OnLoad;
                    bmp.EndInit(); bmp.Freeze();
                    previewImg.Source=bmp;
                    previewBorder.Visibility=Visibility.Visible;
                }catch{previewBorder.Visibility=Visibility.Collapsed;}
            }else{previewBorder.Visibility=Visibility.Collapsed;}
            SetRichText("\u231b \u6b63\u5728\u8bc6\u522b\u4e2d...");
            this.Show(); this.Activate();
        }
        public void ShowResult(string text){SetRichText(text);}
        private void SetRichText(string raw){
            var doc=new System.Windows.Documents.FlowDocument();
            doc.PagePadding=new Thickness(0);
            string[] lns=raw.Replace("\r\n","\n").Replace("\r","\n").Split('\n');
            var curPara=new System.Windows.Documents.Paragraph{Margin=new Thickness(0),LineHeight=double.NaN};
            bool firstBlock=true;
            System.Action flushPara=()=>{
                if(curPara.Inlines.Count>0){doc.Blocks.Add(curPara);firstBlock=false;}
                curPara=new System.Windows.Documents.Paragraph{Margin=new Thickness(0,3,0,0),LineHeight=double.NaN};
            };
            foreach(string line in lns){
                string t=line.TrimEnd();
                if(t.TrimStart('-').Replace("-","").Trim().Length==0&&t.Length>=2&&t.Length<=4){flushPara();continue;}
                if(t.StartsWith("#### ")){flushPara();AddHeading(doc,t.Substring(5),12.5,Color.FromRgb(160,165,220),new Thickness(0,firstBlock?0:6,0,2));firstBlock=false;continue;}
                if(t.StartsWith("### ")){flushPara();AddHeading(doc,t.Substring(4),13.5,Color.FromRgb(140,148,255),new Thickness(0,firstBlock?0:8,0,2));firstBlock=false;continue;}
                if(t.StartsWith("## ")){flushPara();AddHeading(doc,t.Substring(3),14.5,Color.FromRgb(180,186,255),new Thickness(0,firstBlock?0:10,0,2));firstBlock=false;continue;}
                if(t.Length==0){flushPara();continue;}
                if(t.StartsWith("- ")||t.StartsWith("* ")){
                    string content=t.Substring(2);
                    flushPara();
                    var bp=new System.Windows.Documents.Paragraph{Margin=new Thickness(12,1,0,1),LineHeight=double.NaN};
                    var bdot=new System.Windows.Documents.Run("\u2022 ");
                    bdot.Foreground=new SolidColorBrush(Color.FromRgb(99,102,241));
                    bp.Inlines.Add(bdot);
                    AddInlineText(bp,content);
                    doc.Blocks.Add(bp);firstBlock=false;
                    curPara=new System.Windows.Documents.Paragraph{Margin=new Thickness(0,3,0,0),LineHeight=double.NaN};
                    continue;
                }
                AddInlineText(curPara,t);
                curPara.Inlines.Add(new System.Windows.Documents.LineBreak());
            }
            if(curPara.Inlines.Count>0)doc.Blocks.Add(curPara);
            contentBox.Document=doc;
        }
        private void AddHeading(System.Windows.Documents.FlowDocument doc,string text,double fs,Color c,Thickness margin){
            var p=new System.Windows.Documents.Paragraph{Margin=margin,LineHeight=double.NaN};
            var r=new System.Windows.Documents.Run(text);
            r.FontWeight=FontWeights.Bold;r.FontSize=fs;r.Foreground=new SolidColorBrush(c);
            p.Inlines.Add(r); doc.Blocks.Add(p);
        }
        private void AddInlineText(System.Windows.Documents.Paragraph para,string text){
            int i=0;
            while(i<text.Length){
                int si=text.IndexOf("**",i);
                if(si<0){AppendRun(para,text.Substring(i),false);break;}
                if(si>i)AppendRun(para,text.Substring(i,si-i),false);
                int ei=text.IndexOf("**",si+2);
                if(ei<0){AppendRun(para,text.Substring(si),false);break;}
                AppendRun(para,text.Substring(si+2,ei-si-2),true);
                i=ei+2;
            }
        }
        private void AppendRun(System.Windows.Documents.Paragraph para,string text,bool bold){
            if(text.Length==0)return;
            var r=new System.Windows.Documents.Run(text);
            if(bold){r.FontWeight=FontWeights.Bold;r.Foreground=new SolidColorBrush(Color.FromRgb(235,238,255));}
            else{r.Foreground=new SolidColorBrush(Color.FromRgb(200,200,215));}
            para.Inlines.Add(r);
        }
        private void PositionAt(double x,double y){
            double tx=x+20,ty=y+20;
            EnsureWithinScreen(tx,ty);
        }
        private void EnsureWithinScreen(double targetX,double targetY){
            double maxX=SystemParameters.PrimaryScreenWidth-Width;
            double maxY=SystemParameters.PrimaryScreenHeight-Height;
            if(targetX>maxX)targetX=maxX;
            if(targetY>maxY)targetY=maxY;
            if(targetX<0)targetX=0;
            if(targetY<0)targetY=0;
            this.Left=targetX; this.Top=targetY;
        }
    }

    public static class OcrHelper {
        // Uses Windows.Media.Ocr (WinRT) to extract text from PNG bytes
        public static string ExtractText(byte[] pngBytes) {
            try{
                string tmp=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"gamedict_ocr_in.png");
                System.IO.File.WriteAllBytes(tmp,pngBytes);
                // Build powershell command as single-line string
                string ps=
                    "Add-Type -AssemblyName System.Runtime.WindowsRuntime; " +
                    "[void][Windows.Storage.StorageFile,Windows.Storage,ContentType=WindowsRuntime]; " +
                    "[void][Windows.Media.Ocr.OcrEngine,Windows.Foundation,ContentType=WindowsRuntime]; " +
                    "[void][Windows.Globalization.Language,Windows.Foundation,ContentType=WindowsRuntime]; " +
                    "function Aw($t){[System.WindowsRuntimeSystemExtensions]::GetAwaiter($t).GetResult()} " +
                    "$f=Aw([Windows.Storage.StorageFile]::GetFileFromPathAsync('" + tmp.Replace("'","''") + "')); " +
                    "$s=Aw($f.OpenAsync([Windows.Storage.FileAccessMode]::Read)); " +
                    "$bmp=Aw([Windows.Graphics.Imaging.BitmapDecoder]::CreateAsync($s)); " +
                    "$sb=Aw($bmp.GetSoftwareBitmapAsync()); " +
                    "$eng=[Windows.Media.Ocr.OcrEngine]::TryCreateFromUserProfileLanguages(); " +
                    "if(-not $eng -and [Windows.Media.Ocr.OcrEngine]::AvailableRecognizerLanguages.Count -gt 0){$eng=[Windows.Media.Ocr.OcrEngine]::TryCreateFromLanguage([Windows.Media.Ocr.OcrEngine]::AvailableRecognizerLanguages[0])} " +
                    "$r=Aw($eng.RecognizeAsync($sb)); $r.Text";
                var psi=new System.Diagnostics.ProcessStartInfo("powershell.exe","-NoProfile -NonInteractive -Command \"" + ps + "\""){
                    RedirectStandardOutput=true,UseShellExecute=false,CreateNoWindow=true};
                using(var proc=System.Diagnostics.Process.Start(psi)){
                    string text=proc.StandardOutput.ReadToEnd();
                    proc.WaitForExit();
                    return text.Trim();
                }
            }catch(Exception ex){Logger.Error("OcrHelper",ex);return "";}
        }
    }

    public static class Logger {
        private static readonly string LogPath=System.IO.Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"GameDict","gamedict.log");
        private static readonly object _lock=new object();
        static Logger(){try{Directory.CreateDirectory(System.IO.Path.GetDirectoryName(LogPath));}catch{}}
        public static void Info(string m){Write("INFO ",m);}
        public static void Warn(string m){Write("WARN ",m);}
        public static void Error(string m,Exception ex=null){
            Write("ERROR",ex==null?m:m+" | "+ex.GetType().Name+": "+ex.Message+"\n"+ex.StackTrace);}
        private static void Write(string lv,string m){
            try{lock(_lock){
                using(var fs=new FileStream(LogPath,FileMode.Append,FileAccess.Write,FileShare.ReadWrite))
                using(var sw=new StreamWriter(fs,Encoding.UTF8))
                    sw.Write(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff")+" ["+lv+"] "+m+"\n");
            }}catch{}}
    }
    internal static class EmbeddedIcon {
        public static readonly string IcoB64 = "AAABAAYAEBAAAAAAIADyAAAAZgAAACAgAAAAACAAcwEAAFgBAAAwMAAAAAAgAP0BAADLAgAAQEAAAAAAIABQAgAAyAQAAICAAAAAACAAjwQAABgHAAAAAAAAAAAgAIsJAACnCwAAiVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAuUlEQVR4nGNgGGjAiEtCTsnlP7rYo3t7MNQzEasZlzgTsZpxyTOiS544shHOr+vYD2c3VTjC2RY2/nDvMKKbDDKgpG71SRCbi0vEHCb/7dsbsFhPU6g5yAAQABnCxEAhYKLUABZiFS5NmQPxzqM5DAwMHKS5YHZUBwr/4bIfmAY8QkokoIACYXSDnsvthLMxYoEBCrClA2QbYYDR4ghYL4YXsCVX+SiEn2Hg/wkbsEVk5QWQZpgLKAYATL1Hbq8A2fsAAAAASUVORK5CYIKJUE5HDQoaCgAAAA1JSERSAAAAIAAAACAIBgAAAHN6evQAAAE6SURBVHicY2AY6YCRHE1ySi7/cck9ureHJDMZqWEpJY5hopXlxOpjpIXFpIQGEz0sx2ceEz0sx2cuE8MAA0ZCrjxxZCNOzXUd++HspgpHnOosbPxxpgcmfJbTCiDbw8QwwICFGEUldatPYhPn4hIxJ6SmpykUrgYbYKJ38KPbx0KMYly+QE6EhHw6+KNgoADLsIuCpSlzsDiEgz5RsBSr5QwMD5f9IK4olsOSFYktimdHdcDZz+V2wtmSj9zhbPkoDozimImBCgCX5eh8bCHBQshw9IoEK4hC9iE29Rw4o4GJkgYluQBnbUgPR6Cbz0RNw3EFM75cwIRNkNRQQE7d6JYh8xktjjDStFX8EI9PcTmCkRiDSXEINkeALP1/wuY/Nkcw0rNnhM0RjKQaSsgxhNIPyBHY0sKAAQDNqJcammenfAAAAABJRU5ErkJggolQTkcNChoKAAAADUlIRFIAAAAwAAAAMAgGAAAAVwL5hwAAAcRJREFUeJztmT9ugzAUxm0rQ5W5SxYi9RJlYKlUKWOnLnTNETp0ypApQ27QrM3SqWOlSl0Y6CUqwdIrdHNFFZAFBj+DHT8jvikCG37f+2MIJmTSpEGixLCCq1uuGpN/fxi7Lz0XtC0z1BW4KSPUNfhQI4wggu9zfYoFvG82GFZ46H0ZVnjo/bV7AJsY5uhDOBh2eBXPjGgqTd7AYze7z+r39ukGPC+M7sBjmQ/R7+IaXxMHSKPfxqfdA4UeN69fkHHz+eW17pz99r6aA5H3JUR1ywfLKpSf3pO8zwAjnmvWZ9LUxK4zsAdGSWxi3chaNWBKi3zVOPYTvOM3IAMXz2VHQpbxBUHZxC/rQ3Xs4bBuXKc8nx1/QSaYrS9mMpVwBbgMviyhErwwIZPI2QBWPY37Pomf410FCH0SZycD9UyIBrxfRln9gI0y0om+KFkp1fm0m1jn716leMBchaQlZLuZ+yqXcI2vB7BmIW/h6cyAKROqdb1N5XgaJq0c4y0h11nIANH/Pw8FMPW5RTSwlLzryAx2mdCOrgkjkCzQMKE8jbjKhNM9sgwQbZUJL3YpeYcJb/aJeYsJr3bqeRpx1ao0iZxZf5f223PncDwRAAAAAElFTkSuQmCCiVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAACF0lEQVR4nO2bPU7DQBCFZ0Zb5AppgsQlSJEGCYmSigbaHIGCKkUqihwhLTRUlEiRaFKES0TCDVegC7KELStk7f0Z27uz/qpIHr+d93btdZQYYGBgIGWwy8Em51cH09psv+mkNwzFcF+BYOjG2w4CYzHeVhAYm3HuIChm8xzjU5+Dc+HTB3Y9YGiXBEky79IftSneFzZ9EiQOSZt9236JUyw0TPomDpGQaepf+Q6w2745n7t4+ig/Lx8vvfqYzm6cziPJs2/igyBxSPrsN/khSBxKYfbrfCku8YfF66dN/Wp5e+GrodOxgSBxFJeQ70xwaXivgInQ61/njyBxCBJHcQkNu0CkKC4hMbtAahAkjoIIGGfX2mPfk3e5AYxrjP+vGcnaBp/n6/L4/Xqu1S7qvl5+4Oxu5B9Att9gn4/DpsaPL4F8JeQh5NQFcfzTmYLQtsFsXRpbLcFYMzddBBDtLjD+u55db2zFzNsEQSDEvGsI1Oc/tLrmlC/UFXd5IzS5eXFongqAdALSVoHOD0HiUN1BKaugzgdB4lBTQeyroKl/4hCJGTItbDMElye4OgodnG4beyZIHLIpjmEV2My+0woIOQRb8zleZtp4XK6at3k0Pg7NNAQET9r6zmAaRLUuN33YzQ42ISAw0EUITVTN2oSAwEgfQegMmoaAIPidIZMQEIS/NdYUAkIC7w3a3hhFUg1hYABKfgF8nw6H5KrOdQAAAABJRU5ErkJggolQTkcNChoKAAAADUlIRFIAAACAAAAAgAgGAAAAwz5hywAABFZJREFUeJztnT1uFEEQhWctAl9hE6/EJXDgBAmJkIgEUh9hAyIHjgg4glOTEBEiIZE4sC+BtJNwBTKjtbQSgp3pn6mqftX1vgQJ2bM9/b6u/pmxPQyEEEIIIYQQQgiJwmoIwNnzV4+13zv+/N51H3V3c0vCjiiF+xuxCLxnIVw2HCH0XmRw1Vjk4L2KAN9IT6F7lAG2YT0E70GEkwGQHsNHvS8oIxE7qPdqANGISMGjidB8CogcPsL9n0S+eRRa9kOT8sPgcaYE8wrA8LH6x1QAho/XT2YCMHzM/jIRgOHj9pu6AAwfu/9UBWD4+P2oJgDD99GfKgIwfB00+lVcAIavi3T/Nn8WQNoiKgBHvw2S/SwmAMO3Raq/RQRg+G2Q6HeuAYKzamnh/d3XoRVXH3/893/XH14OrTi/eNPkETIrQHAWCcC5H4MlOVQLwPCxqM2DU0BwqgTg6MekJhdWgOBQgOAUC8Dyj01pPqwAwSkSgKPfByU5sQIE59kAxPbqy4Pm9T9dv33hsS2aZFcAln9f5ObFKSA4UFMASllEa4smrADByRKA879PcnJjBQgOBQgOBQgOBQhOUgAuAH2Tyo8VIDgUIDhQJ4FID2C2QG3RhBUgOBQgOFBTAEpZRGuLJqwAwaEAwaEAwaEAwaEAwYHaBfTCenyd/JpfZ98GBCiAUeDp7zkdWkABjIOfYvf599O/m3enWGuA1n/WDDX4tWD4/4pwkEGCVH5QFQDpAcx2oi23lzcmJ4R7CSyqAZQA6Nxmhv/+5vJB4loWElCADHLCygl9ahcwN51orw2y5net18I8/KLIdWKul9rO7X9RZGrur5EgtQbIOgjiQtBmLy89ynNy40ngDFOjfx+81kHOXoIpESR3BwcoQEX4FlhJQAEAw7eUIFsArgN8kZsXKwDo6LeqAhQgg9ZP7jQPg4rLes8/KrabGFXWD2iWtq1kumYFSIAQvmY7igXgYhCb0nxYAYJDAWbmWJTyP9eepbuBKgE4DWBSkwsrQHCqBWAVwKI2j0UVgBJgwD8cSYZmArAK+IYVIDgiArAK+EWsAniXYKNwyCLNsfaszu9WMFOAdwkiwjVAcMQF6K0K7ECmAa12qFQArxJswB7+pFg6/6tOAV4lQKwCmp+vugbwKMHG8Icycpj6XInRb7II9ChBJEx2Ad4k2IBUAe3Rb7oNpAR44T9dbzDG22vlu5nANXYNc58nHX6TgyBvlWAO6WqQut7j/YX44GkahpdqsMsIekk1KBVJshI0H41eJCgJKkeG3Gvtwz428qUkaC5ArxJI8HfIWhJACOBNhJ2BBMfC1ZAASoADkUVYJQKVlgBSAE8SSIlQEqKkBLACeBShRIilpVtKAngBvMowGpx3SEjgSgAPIozGB11LJXApAJoMY+PTzSUSuBeghRAj4HF2rQRwN4ImxQgYtqQEbm6O6EjA18I7I/cE8QAFCCCBxnsExAEa7w8QQgjphj/84eovxuFY4QAAAABJRU5ErkJggolQTkcNChoKAAAADUlIRFIAAAEAAAABAAgGAAAAXHKoZgAACVJJREFUeJzt3b1uHNcZgOFdIUVuQc0a8E1EhRoDBlK6SpO0voQUrlSocpEiF+A2alIZcJPAgBsVyk0YWDa6BXcMJoFjmRG5f+fMfD/P09iAJXp5Zr53zgzJ5W4HAAAAAAAAAAAAAAAAAAAARLPf+gUwx+HTz+9Hf8y7H793vhTjgCY1Y8BvJRD5OGAJRBz2c4lCbA5OQJkH/hRBiMXBCKDywJ8iCNuy+BvpPPSPEYP1WfAVGfrzicE6LPJkhv52YjCPhZ3E4I8nBONZ0IEM/XrEYAyLOIDB344Q3Mbi3cDgxyEE17FoVzD4cQnBZSzWBQx+HkJwHot0BoOflxA87dmJ/96e4c/N8XuaOj7CiVOP3cD/syAPGPz6hOAXbgE+YPh7cJx/oYROiNbumu8G2u8ADH9vh+bHv3UAuh98/qvzedBy+9P5gPO0u2a3BO12AIafpxyanR+tAtDt4HKdQ6PzpMV2p9MBZay74rcE5XcAhp9bHIqfP6UDUP3gsY5D4fOobAAqHzTWdyh6PpUMQNWDxbYOBc+rcgGoeJCI41Ds/CoVgGoHh5gOhc6zMgGodFCI71DkfCsRgCoHg1wOBc679AGocBDI65D8/EsdgOyLTw2HxOdh2gBkXnTqOSQ9H1MGIOtiU9sh4XmZLgAZF5k+DsnOz1QByLa49HRIdJ6mCUCmRYVDkvM1RQCyLCZkO29TBABoGoAMFYWs52/oAERfPMh+HocNQORFgyrnc9gAAE0DELWWUO28DheAiIsEVc/vUAGItjhQ/TwPFQCgaQAiVRG6nO8hAhBlMaDbeR8iAMA29l0r+O7tt7uOXn39w8k/8/qrz3ZdvXj5RatfQGoHAI09634PBFvbcg42C4Dhh+3nwS0ANLZJAFz9IcZc2AFAY6sHwNUf4syHHQA0tmoAXP0h1pzYAUBjqwXA1R/izYsdADS2SgBc/SHm3NgBQGMCAI1ND4DtP8SdHzsAaGxqAFz9IfYc2QFAYwIAjU0LgO0/xJ8nOwBoTACgsd/M+KAVtv9/fvX3f+2S+svrP/xu1sfOvC6z12a2Za5G/w4BOwBoTACgseEBqLD9h6hGz5cdADQ25SFgBZkfFs1kXWqxA4DGhgbA/T/MN3LO7ACgMQGAxgQAGhsWAPf/sJ5R82YHAI0JADQmANCYAEBjQwLgASCsb8Tc2QFAYwIAjQkANCYA0JgAQGMCAI0JADR2cwB8DwBs59b5swOAxgQAGvOuwAV/BZZfDfY472r8a3YA0JgAQGMCAI0JADTmIeAjPCz6OOtSix0ANCYA0JgAQGMCAI0JADQmANCYAEBjAgCNCQA0JgDQmABAY34WgHSe3/3+4r/z/vCPKa9l1z0Adz9+v/fGoEQa9nM/zvsCUVjm75a/bwdA2aG/5P/zvkAMriEAtBr6U///45vd7pM//nbXhQDQevA/5vjmp//8s0MIBIBNRBz8jiEQAFaVYfA7hUAAWEXGwe8QAt8IxHQVhv9jIajgWYSvRVJXteGPFIERc+cWoOCvwIrwq8H+9uU3017Dn7758uJjM+P1HAvcEggAw40etmsG/rGP8XMcR+5Mjm9+ShsBASDk8I8Y+qd8+J1/zwfEIGsEBIBQwz978J+KwfMbQ5AxAsO+CuBBYG+3Dv8y+FsM/8MQ3DrAaz0cHDVvQ4c2008Fvnv77a6jV1//cPLPvP7qs4s+5i1Xzmg/hPPi5RdDhnn2TmBUAHwfADepNPwjhzjClwnPIQCsPvzL4Ecf/g8jcG0IMkRgaAA8B+CULIP/UKSHeyPnzA6Aq3R8W65ProhA9F2AAHCxjsNfNQICwEU6D3/FCAwPgOcAVB7+rZ8JjJ4vOwCmXf2rDv+1EYi4CxAApqg+/BG/OhAmAG4D6qn6c/1ru2UXMGOu7AAYrsvVv8IuQAAYevXvNvzXRCDSs4BpAXAbAPHnyQ6AJ7n6194FtH1DkA9/7JNf++d3f/3fvy+/Kutc1jSfqTsAtwF9ZH4QFn0dZs6RWwDCb1OrOgZY3+kBsAuoz9V/3nrMnh87AGhMAAi7Pe3guPE6rxIAtwF12f7PW5c15sYOABpbLQB2ARBvXuwAoLFVA2AXUOvBlPv/MevzcL3XnBM7AGhs9QDYBUCc+bADgMY2CYBdAMSYCzsAaGyzANgFwPbzsOkOQARgW24BoLHNA2AXAI0DADQPgF0ANA7AQgSgcQDI/0MsXLc++xdvN7v4hQqAXQA0DsBCBKBxABYiAI0DQB6eA+Rel7ABsAvYlnf7WceWDwBDB2AhAtA4AAsRiC/Ldnctx0TrET4AbMdtQO3tf5oA2AXEl+mqN9Mx2TqkCMBCBKBxABYiEPs2INvVb7RLPv8I2/90AViIADQOwEIE1mUXUPPqnzYACxGIq1sEjok/37QBWIjAenxJcIxIV//0AViIQEyZr4qdPs/0AViIQMxdQPbhGP35Rbv6lwnAQgRiqhqBY5HPq0wAFiIQ81lAlWG55fOJePUvF4CFCMzXOQLHQsNfMgALEZivYwSOxYa/bAAWIhBT1ggck77uU8oPyeHTz++3fg2V3TIYGb634Dhg8CPvAsruAH5mJzDXLUMc/ap6HPT67t+9DHsRajUcdgNxhyXSbuA4KUwRdwLhXtBsIhB7cLYMwXGFHUm0CIR6MWsRgfhDtGYIjivfikSKQJgXsgUhyDFQM2Kw9fOHfZAIhHgRWxKBOWYOWJXvQdgHiMDmLyACEZgn4uCNHuD7G57ybx0BAfiAEMxRMQL7B4ObNQLlvw/gEr5nYI5IX+IbYf+Rgb1liLf8PgEn/CPsBubIvBvYnzHk2XYCAnCCEMyRKQT7CwczUwQE4Awi0DME+4229WtGQAAuIAQ9QrAfNIAZIiAAVxCCejHYTxq46BEQgBsIQe4Y7Fe6ykaOgAAMIATryvjOPPdBIyAAAwnBejJ+z8Z9wAikW8QsxGC8jEMfPQLpFzQ6IbhdhcGPGoFSCxudGPQd+qgRKL3IkYlBv6GPGIFWCx5V5xh0G/poEWi9+FFVDkL3gY8WAQcjgcxBMPCxI+DgJBUxCoY9XwQcsKJmBMKA14uAAwqNI+AtwaDx+xAIADSOgABA4wgIAAR29dP9M/+eAECxCFzy5wUAEjh3qH0VAIranxjua24XBAASeWzIr31WIACQzMNh3/r9DoENbPk7BQEAAIBdKv8GkkupVWtmzAwAAAAASUVORK5CYII=";
        public static string ExtractToTemp(){
            try{
                byte[] bytes=Convert.FromBase64String(IcoB64);
                string path=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"gamedict_icon.ico");
                File.WriteAllBytes(path,bytes);return path;
            }catch{return null;}
        }
    }
}